#!/usr/bin/python

import imaplib

try:
    # private gmail
    gmail = imaplib.IMAP4_SSL('imap.gmail.com',993)
    gmail.login('stevenklar0@gmail.com','skkalqzhgugrwejz')
    gmail.select()
    gmail_len = len(gmail.search(None, 'UnSeen')[1][0].split())

    # private gmail
    fewo = imaplib.IMAP4_SSL('outlook.office365.com',993)
    fewo.login('klar@bestfewo.de','Thorsten107464')
    fewo.select()
    fewo_len = len(fewo.search(None, 'UnSeen')[1][0].split())

    # output
    if gmail_len > 0 or fewo_len > 0:
        print 'G' + str(gmail_len) + ' B'+ str(fewo_len)
    else:
        print '0'
except:
    print 'Offline'


# coding: utf-8
